import { NextResponse } from "next/server";
import { getCurrentUser } from "@/server/session";
import { getSkillStrengths } from "@/server/skills";
import { localCoachTip } from "@/server/adaptive";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

/**
 * Returns a short practice tip. If ANTHROPIC_API_KEY is configured the tip is
 * generated by Claude from the user's recent numbers; otherwise a solid local
 * heuristic is used, so the feature always works.
 */
export async function GET() {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "unauth" }, { status: 401 });

  const [progress, strengths] = await Promise.all([
    prisma.progress.findUnique({ where: { userId: user.id } }),
    getSkillStrengths(user.id),
  ]);

  const values = Object.values(strengths);
  const weakest = values.length ? Math.min(...values) : 1;
  const stats = {
    streak: progress?.streak ?? 0,
    dailyXp: progress?.dailyXp ?? 0,
    dailyGoalXp: user.dailyGoalXp,
    weakestStrength: weakest,
  };

  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) {
    return NextResponse.json({ tip: localCoachTip(stats), source: "local" });
  }

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": key,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 120,
        system:
          "Você é um professor de violão/baixo amigável. Responda em português do Brasil com UMA dica curta e prática (máx. 2 frases) baseada nos números do aluno. Sem emojis em excesso.",
        messages: [
          {
            role: "user",
            content: `Streak: ${stats.streak} dias. XP hoje: ${stats.dailyXp}/${stats.dailyGoalXp}. Habilidade mais fraca (0-1): ${weakest.toFixed(
              2
            )}. Instrumento: ${user.instrument === "BASS" ? "baixo" : "guitarra"}. Dê a dica de hoje.`,
          },
        ],
      }),
    });
    if (!res.ok) throw new Error(String(res.status));
    const data = (await res.json()) as {
      content?: { text?: string }[];
    };
    const tip = data.content?.[0]?.text?.trim();
    return NextResponse.json({
      tip: tip || localCoachTip(stats),
      source: tip ? "claude" : "local",
    });
  } catch {
    return NextResponse.json({ tip: localCoachTip(stats), source: "local" });
  }
}
